# This is a sample Dockerfile you can modify to deploy your own app based on face_recognition

FROM python:3.9.0rc1-buster
# FROM continuumio/anaconda

RUN apt-get -y update
RUN apt-get install -y --fix-missing \
    build-essential \
    cmake \
    gfortran \
    git \
    wget \
    curl \
    graphicsmagick \
    libgraphicsmagick1-dev \
    libatlas-base-dev \
    libavcodec-dev \
    libavformat-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    liblapack-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    software-properties-common \
    zip \
    && apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN cd ~ && \
    mkdir -p dlib && \
    git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS

# Set working directory to this app
WORKDIR /app

# copy and install the requirements
COPY /requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install opencv-python

# Copy the current directory contents into the container
COPY . /app

# set port
EXPOSE 5000

# run the command to start the app
ENTRYPOINT [ "python3" ]
CMD [ "run.py" ]
